allow-lan: true
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
listeners:
  - name: mixedC1
    type: mixed
    port: 43000
    proxy: ğŸ”— é“¾å¼ä»£ç†1
  - name: mixedC2
    type: mixed
    port: 43001
    proxy: ğŸ”— é“¾å¼ä»£ç†2
  - name: mixedC3
    type: mixed
    port: 43002
    proxy: ğŸ”— é“¾å¼ä»£ç†3
  - name: mixed0
    type: mixed
    port: 42000
    proxy: JPä¸“çº¿0001
  - name: mixed1
    type: mixed
    port: 42001
    proxy: USä¸“çº¿0001
  - name: mixed2
    type: mixed
    port: 42002
    proxy: ğŸ‡­ğŸ‡° é¦™æ¸¯ 01
  - name: mixed3
    type: mixed
    port: 42003
    proxy: ğŸ‡­ğŸ‡° é¦™æ¸¯ 02
  - name: mixed4
    type: mixed
    port: 42004
    proxy: ğŸ‡­ğŸ‡° é¦™æ¸¯ 03
  - name: mixed5
    type: mixed
    port: 42005
    proxy: ğŸ‡­ğŸ‡° é¦™æ¸¯ 04
  - name: mixed6
    type: mixed
    port: 42006
    proxy: ğŸ‡­ğŸ‡° é¦™æ¸¯ 05
  - name: mixed7
    type: mixed
    port: 42007
    proxy: ğŸ‡¹ğŸ‡¼ å°æ¹¾ 01
  - name: mixed8
    type: mixed
    port: 42008
    proxy: ğŸ‡¹ğŸ‡¼ å°æ¹¾ 02
  - name: mixed9
    type: mixed
    port: 42009
    proxy: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 01
  - name: mixed10
    type: mixed
    port: 42010
    proxy: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 02
  - name: mixed11
    type: mixed
    port: 42011
    proxy: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 03
  - name: mixed12
    type: mixed
    port: 42012
    proxy: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 01
  - name: mixed13
    type: mixed
    port: 42013
    proxy: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 02
  - name: mixed14
    type: mixed
    port: 42014
    proxy: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 03
  - name: mixed15
    type: mixed
    port: 42015
    proxy: ğŸ‡°ğŸ‡· éŸ©å›½
  - name: mixed16
    type: mixed
    port: 42016
    proxy: ğŸ‡ºğŸ‡¸ ç¾å›½ 01
  - name: mixed17
    type: mixed
    port: 42017
    proxy: ğŸ‡ºğŸ‡¸ ç¾å›½ 02
  - name: mixed18
    type: mixed
    port: 42018
    proxy: ğŸ‡ºğŸ‡¸ ç¾å›½ 03
  - name: mixed19
    type: mixed
    port: 42019
    proxy: ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§
  - name: mixed20
    type: mixed
    port: 42020
    proxy: ğŸ‡»ğŸ‡³ è¶Šå—
  - name: mixed21
    type: mixed
    port: 42021
    proxy: ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºš
  - name: mixed22
    type: mixed
    port: 42022
    proxy: ğŸ‡¹ğŸ‡­ æ³°å›½
  - name: mixed23
    type: mixed
    port: 42023
    proxy: ğŸ‡®ğŸ‡³ å°åº¦
  - name: mixed24
    type: mixed
    port: 42024
    proxy: ğŸ‡µğŸ‡­ è²å¾‹å®¾
  - name: mixed25
    type: mixed
    port: 42025
    proxy: ğŸ‡®ğŸ‡© å°å°¼
  - name: mixed26
    type: mixed
    port: 42026
    proxy: ğŸ‡¦ğŸ‡º æ¾³å¤§åˆ©äºš
  - name: mixed27
    type: mixed
    port: 42027
    proxy: ğŸ‡³ğŸ‡¿ æ–°è¥¿å…°
  - name: mixed28
    type: mixed
    port: 42028
    proxy: ğŸ‡©ğŸ‡ª å¾·å›½
  - name: mixed29
    type: mixed
    port: 42029
    proxy: ğŸ‡«ğŸ‡· æ³•å›½
  - name: mixed30
    type: mixed
    port: 42030
    proxy: ğŸ‡¨ğŸ‡­ ç‘å£«
  - name: mixed31
    type: mixed
    port: 42031
    proxy: ğŸ‡¬ğŸ‡§ è‹±å›½
  - name: mixed32
    type: mixed
    port: 42032
    proxy: ğŸ‡µğŸ‡± æ³¢å…°
  - name: mixed33
    type: mixed
    port: 42033
    proxy: ğŸ‡®ğŸ‡¹ æ„å¤§åˆ©
  - name: mixed34
    type: mixed
    port: 42034
    proxy: ğŸ‡ªğŸ‡¸ è¥¿ç­ç‰™
  - name: mixed35
    type: mixed
    port: 42035
    proxy: ğŸ‡³ğŸ‡± è·å…°
  - name: mixed36
    type: mixed
    port: 42036
    proxy: ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯
  - name: mixed37
    type: mixed
    port: 42037
    proxy: ğŸ‡ºğŸ‡¦ ä¹Œå…‹å…°
  - name: mixed38
    type: mixed
    port: 42038
    proxy: ğŸ‡ªğŸ‡¬ åŸƒåŠ
  - name: mixed39
    type: mixed
    port: 42039
    proxy: ğŸ‡³ğŸ‡¬ å°¼æ—¥åˆ©äºš
  - name: mixed40
    type: mixed
    port: 42040
    proxy: ğŸ‡²ğŸ‡© æ‘©å°”å¤šç“¦
  - name: mixed41
    type: mixed
    port: 42041
    proxy: ğŸ‡µğŸ‡° å·´åŸºæ–¯å¦
  - name: mixed42
    type: mixed
    port: 42042
    proxy: ğŸ‡ºğŸ‡¿ ä¹Œå…¹åˆ«å…‹æ–¯å¦
  - name: mixed43
    type: mixed
    port: 42043
    proxy: ğŸ‡¹ğŸ‡· åœŸè€³å…¶
  - name: mixed44
    type: mixed
    port: 42044
    proxy: ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·
  - name: mixed45
    type: mixed
    port: 42045
    proxy: ğŸ‡§ğŸ‡· å·´è¥¿
  - name: mixed46
    type: mixed
    port: 42046
    proxy: ğŸ‡²ğŸ‡½ å¢¨è¥¿å“¥
  - name: mixed47
    type: mixed
    port: 42047
    proxy: ğŸ‡¨ğŸ‡± æ™ºåˆ©
proxies:
  - name: JPä¸“çº¿0001
    type: socks5
    server: sp-us1.kookeey.info
    port: 16658
    username: zhuxietong
    password: '11111111'
  - name: USä¸“çº¿0001
    type: http
    server: us10.kookeey.info
    port: 27691
    username: zhuxietong
    password: '11111111'
  - name: MLä¸“çº¿0001
    type: socks5
    server: 46.3.158.187
    port: 8000
    username: TQvfvW
    password: U8EaBp
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 01
    type: ss
    server: lienbagh.yangliq.com
    port: 21101
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 02
    type: ss
    server: lienbagh.yangliq.com
    port: 21102
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 03
    type: ss
    server: lienbagh.yangliq.com
    port: 21103
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 04
    type: ss
    server: lienbagh.yangliq.com
    port: 21004
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯ 05
    type: ss
    server: lienbagh.yangliq.com
    port: 21005
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¹ğŸ‡¼ å°æ¹¾ 01
    type: ss
    server: lienbagh.yangliq.com
    port: 22001
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¹ğŸ‡¼ å°æ¹¾ 02
    type: ss
    server: lienbagh.yangliq.com
    port: 22002
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 01
    type: ss
    server: lienbagh.yangliq.com
    port: 24001
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 02
    type: ss
    server: lienbagh.yangliq.com
    port: 24002
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬ 03
    type: ss
    server: lienbagh.yangliq.com
    port: 24003
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 01
    type: ss
    server: lienbagh.yangliq.com
    port: 23001
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 02
    type: ss
    server: lienbagh.yangliq.com
    port: 23002
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡ 03
    type: ss
    server: lienbagh.yangliq.com
    port: 23003
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡°ğŸ‡· éŸ©å›½
    type: ss
    server: lienbagh.yangliq.com
    port: 25001
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½ 01
    type: ss
    server: lienbagh.yangliq.com
    port: 26001
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½ 02
    type: ss
    server: lienbagh.yangliq.com
    port: 26002
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½ 03
    type: ss
    server: lienbagh.yangliq.com
    port: 26003
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§
    type: ss
    server: lienbagh.yangliq.com
    port: 27014
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡»ğŸ‡³ è¶Šå—
    type: ss
    server: lienbagh.yangliq.com
    port: 27024
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºš
    type: ss
    server: lienbagh.yangliq.com
    port: 27018
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¹ğŸ‡­ æ³°å›½
    type: ss
    server: lienbagh.yangliq.com
    port: 27016
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡®ğŸ‡³ å°åº¦
    type: ss
    server: lienbagh.yangliq.com
    port: 27020
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡µğŸ‡­ è²å¾‹å®¾
    type: ss
    server: lienbagh.yangliq.com
    port: 27001
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡®ğŸ‡© å°å°¼
    type: ss
    server: lienbagh.yangliq.com
    port: 27019
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¦ğŸ‡º æ¾³å¤§åˆ©äºš
    type: ss
    server: lienbagh.yangliq.com
    port: 27008
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡³ğŸ‡¿ æ–°è¥¿å…°
    type: ss
    server: lienbagh.yangliq.com
    port: 27028
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡©ğŸ‡ª å¾·å›½
    type: ss
    server: lienbagh.yangliq.com
    port: 27004
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡«ğŸ‡· æ³•å›½
    type: ss
    server: lienbagh.yangliq.com
    port: 27023
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¨ğŸ‡­ ç‘å£«
    type: ss
    server: lienbagh.yangliq.com
    port: 27007
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¬ğŸ‡§ è‹±å›½
    type: ss
    server: lienbagh.yangliq.com
    port: 27005
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡µğŸ‡± æ³¢å…°
    type: ss
    server: lienbagh.yangliq.com
    port: 27010
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡®ğŸ‡¹ æ„å¤§åˆ©
    type: ss
    server: lienbagh.yangliq.com
    port: 27012
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡ªğŸ‡¸ è¥¿ç­ç‰™
    type: ss
    server: lienbagh.yangliq.com
    port: 27026
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡³ğŸ‡± è·å…°
    type: ss
    server: lienbagh.yangliq.com
    port: 27027
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯
    type: ss
    server: lienbagh.yangliq.com
    port: 27025
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡ºğŸ‡¦ ä¹Œå…‹å…°
    type: ss
    server: lienbagh.yangliq.com
    port: 27022
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡ªğŸ‡¬ åŸƒåŠ
    type: ss
    server: lienbagh.yangliq.com
    port: 27021
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡³ğŸ‡¬ å°¼æ—¥åˆ©äºš
    type: ss
    server: lienbagh.yangliq.com
    port: 27029
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡²ğŸ‡© æ‘©å°”å¤šç“¦
    type: ss
    server: lienbagh.yangliq.com
    port: 27013
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡µğŸ‡° å·´åŸºæ–¯å¦
    type: ss
    server: lienbagh.yangliq.com
    port: 27017
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡ºğŸ‡¿ ä¹Œå…¹åˆ«å…‹æ–¯å¦
    type: ss
    server: lienbagh.yangliq.com
    port: 27015
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¹ğŸ‡· åœŸè€³å…¶
    type: ss
    server: lienbagh.yangliq.com
    port: 27003
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¦ğŸ‡· é˜¿æ ¹å»·
    type: ss
    server: lienbagh.yangliq.com
    port: 27006
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡§ğŸ‡· å·´è¥¿
    type: ss
    server: lienbagh.yangliq.com
    port: 27009
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡²ğŸ‡½ å¢¨è¥¿å“¥
    type: ss
    server: lienbagh.yangliq.com
    port: 27011
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
  - name: ğŸ‡¨ğŸ‡± æ™ºåˆ©
    type: ss
    server: lienbagh.yangliq.com
    port: 27002
    cipher: aes-128-gcm
    password: f8308ffa-0b18-44f8-aa02-8b466bc6e6df
    udp: true
proxy-groups:
  - name: "ğŸ”— é“¾å¼ä»£ç†1"
    type: relay
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯ 01
      - JPä¸“çº¿0001
  - name: "ğŸ”— é“¾å¼ä»£ç†2"
    type: relay
    proxies:
      - ğŸ‡ºğŸ‡¸ ç¾å›½ 01
      - USä¸“çº¿0001
  - name: "ğŸ”— é“¾å¼ä»£ç†3"
    type: relay
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯ 01
      - MLä¸“çº¿0001